site_name: "CR3"
site_description: "Finding and Reparing LTL specifications using Contracts"
site_url: ""
repo_url: "https://github.com/pierg/cr3"
repo_name: "cr3"
site_dir: "site"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md, src/cr3]

nav:
- Home:
  - Overview: index.md
  - Getting started: getting_started.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Development:
  - Contributing: contributing.md
  - Coverage report: coverage.md


theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - toc.integrate
  font:
    #text: Eczar
    #text: Alegreya Sans
    #text: Roboto Slab
    #text: Inknut Antiqua
    text: Libre Baskerville
    #text: Cardo
    code: Roboto Mono
    #text: Merriweather
    #code: Inconsolata
  palette:
    scheme: default
    primary: white
    accent: purple
#  - media: "(prefers-color-scheme: light)"
#    scheme: default
#    primary: teal
#    accent: purple
#    toggle:
#      icon: material/weather-sunny
#      name: Switch to dark mode
#  - media: "(prefers-color-scheme: dark)"
#    scheme: slate
#    primary: black
#    accent: lime
#    toggle:
#      icon: material/weather-night
#      name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - callouts
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
- search
- mkdocs-jupyter
- mkdocs-video
- markdown-exec
- gen-files:
    scripts:
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- coverage
- section-index
- mkdocstrings

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/github_username
